const courses = [
  {
    courseCode: 'CS101',
    courseTitle: 'Introduction to Computer Science',
    lecturer: 'Dr. Smith',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'CS202',
    courseTitle: 'Data Structures and Algorithms',
    lecturer: 'Prof. Johnson',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'ENG303',
    courseTitle: 'Advanced Writing Workshop',
    lecturer: 'Dr. Miller',
    courseUnitWeight: 1,
  },
  {
    courseCode: 'MATH204',
    courseTitle: 'Linear Algebra and Calculus',
    lecturer: 'Dr. Davis',
    courseUnitWeight: 2,
  },
  {
    courseCode: 'PHYS205',
    courseTitle: 'Modern Physics',
    lecturer: 'Prof. Anderson',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'CHEM206',
    courseTitle: 'Organic Chemistry',
    lecturer: 'Dr. Wilson',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'HIST317',
    courseTitle: 'World History',
    lecturer: 'Prof. Thompson',
    courseUnitWeight: 2,
  },
  {
    courseCode: 'PSYC108',
    courseTitle: 'Introduction to Psychology',
    lecturer: 'Dr. Robinson',
    courseUnitWeight: 1,
  },
  {
    courseCode: 'ART409',
    courseTitle: 'Art Appreciation',
    lecturer: 'Prof. Turner',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'ECON110',
    courseTitle: 'Principles of Economics',
    lecturer: 'Dr. White',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'BIO111',
    courseTitle: 'Biology Fundamentals',
    lecturer: 'Dr. Adams',
    courseUnitWeight: 2,
  },
  {
    courseCode: 'STAT201',
    courseTitle: 'Statistics for Beginners',
    lecturer: 'Prof. Garcia',
    courseUnitWeight: 1,
  },
  {
    courseCode: 'PHIL131',
    courseTitle: 'Introduction to Philosophy',
    lecturer: 'Dr. Brown',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'LANG401',
    courseTitle: 'Language and Communication',
    lecturer: 'Dr. Martinez',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'EDUC205',
    courseTitle: 'Foundations of Education',
    lecturer: 'Prof. Clark',
    courseUnitWeight: 2,
  },
  {
    courseCode: 'SOC306',
    courseTitle: 'Sociology Basics',
    lecturer: 'Dr. Lewis',
    courseUnitWeight: 1,
  },
  {
    courseCode: 'GEOL227',
    courseTitle: 'Geology Exploration',
    lecturer: 'Prof. Carter',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'COMM108',
    courseTitle: 'Communication Skills',
    lecturer: 'Dr. Turner',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'PHARMA209',
    courseTitle: 'Pharmacology Essentials',
    lecturer: 'Dr. Harris',
    courseUnitWeight: 2,
  },
  {
    courseCode: 'MUSIC420',
    courseTitle: 'Music Theory',
    lecturer: 'Prof. Wright',
    courseUnitWeight: 1,
  },
  {
    courseCode: 'ANTHRO211',
    courseTitle: 'Cultural Anthropology',
    lecturer: 'Dr. King',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'POLSCI210',
    courseTitle: 'Political Science Principles',
    lecturer: 'Prof. Adams',
    courseUnitWeight: 3,
  },
  {
    courseCode: 'BUSINESS321',
    courseTitle: 'Introduction to Business',
    lecturer: 'Dr. Taylor',
    courseUnitWeight: 2,
  },
  {
    courseCode: 'LING240',
    courseTitle: 'Linguistics Fundamentals',
    lecturer: 'Dr. Martinez',
    courseUnitWeight: 1,
  },
  {
    courseCode: 'ARCH215',
    courseTitle: 'Architectural Design Basics',
    lecturer: 'Prof. Adams',
    courseUnitWeight: 3,
  },
];

export default courses;
