// Student data
const students = [
  {
    firstName: 'John',
    lastName: 'Doe',
    middleName: 'Terry',
    year: '100L',
    faculty: 'Engineering',
    department: 'Computer Science',
    studentId: '23/1234',
    maritalStatus: 'Single',
    nationality: 'US',
    address: '123 Main St, City',
    email: 'john.doe@email.com',
    phoneNumber: '123-456-7890',
    password: 'password123',
    dateOfBirth: '2001-05-15',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    middleName: 'Ann',
    year: '200L',
    faculty: 'Business',
    department: 'Finance',
    studentId: '22/5678',
    maritalStatus: 'Married',
    nationality: 'Canada',
    address: '456 Oak St, Town',
    email: 'jane.smith@email.com',
    phoneNumber: '987-654-3210',
    password: 'pass456word',
    dateOfBirth: '2000-02-22',
  },
  {
    firstName: 'Bob',
    lastName: 'Johnson',
    middleName: 'Peter',
    year: '300L',
    faculty: 'Science',
    department: 'Biology',
    studentId: '21/9012',
    maritalStatus: 'Single',
    nationality: 'UK',
    address: '789 Pine St, Village',
    email: 'bob.johnson@email.com',
    phoneNumber: '345-678-9012',
    password: 'bobpassword',
    dateOfBirth: '1999-11-05',
  },
  {
    firstName: 'Alice',
    lastName: 'Williams',
    middleName: 'Grace',
    year: '400L',
    faculty: 'Arts',
    department: 'History',
    studentId: '20/3456',
    maritalStatus: 'Single',
    nationality: 'Australia',
    address: '101 Cedar St, Hamlet',
    email: 'alice.williams@email.com',
    phoneNumber: '567-890-1234',
    password: 'alicepass',
    dateOfBirth: '1998-09-18',
  },
  {
    firstName: 'Charlie',
    lastName: 'Brown',
    middleName: 'Michael',
    year: '100L',
    faculty: 'Social Sciences',
    department: 'Psychology',
    studentId: '23/7890',
    maritalStatus: 'Single',
    nationality: 'Nigeria',
    address: '202 Elm St, Borough',
    email: 'charlie.brown@email.com',
    phoneNumber: '210-987-6543',
    password: 'charliepass',
    dateOfBirth: '2002-04-10',
  },
];

export default students;
